# Generated by Django 5.0.3 on 2024-03-12 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_amenityinfo_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_month_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_fee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_fee_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='charge_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='data.chargeinfo'),
        ),
    ]
