# Generated by Django 5.0.3 on 2024-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_chargeinfo_property_charge_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='chargeinfo',
            name='extra_fee',
            field=models.ManyToManyField(blank=True, related_name='charges', to='data.extrafee'),
        ),
    ]
