# Generated by Django 5.0.3 on 2024-03-13 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_extrafee_chargeinfo_extra_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
