# Generated by Django 5.0.3 on 2024-03-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_extrafee_created_at_extrafee_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.BooleanField(default=False)),
                ('sewage', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('garbage', models.BooleanField(default=False)),
                ('cable', models.BooleanField(default=False)),
                ('satellite_tv', models.BooleanField(default=False)),
                ('other_utilities', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='utility_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='data.utilityinformation'),
        ),
    ]
