# Generated by Django 5.0.3 on 2024-03-13 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_utilityinformation_property_utility_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilityinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
