# Generated by Django 5.0.3 on 2024-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_address_floor_alter_chargeinfo_application_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='bathrooms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='bedrooms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
